/* 

ĐÂY LÀ CƠ SỞ DỮ LIỆU BÀI TẬP QUẢN LÝ ĐỀ ÁN ĐÃ ĐƯỢC GIẢI FULL, CHỈ CẦN ẤN F5 HOẶC EXECUTE CÂU LỆNH ĐÚNG 100%

THÔNG TIN NGƯỜI GIẢI DATABASE NÀY:
HỌ TÊN: NGUYỄN HOÀNG HUY
LỚP: CĐ9+TH.QTM1-K11
CÁC BẠN CẦN HỖ TRỢ VỀ SQL SERVER CỨ NHẮN TIN QUA ZALO: 033.293.6390

CHÚC CÁC BẠN HỌC TỐT !

*/

CREATE DATABASE QuanLyDeAn -- CÂU LỆNH TẠO DATABASE --
GO

USE QuanLyDeAn -- CÂU LỆNH GỌI SỬ DỤNG DATABASE --
GO


-- TẠO BẢNG & KHOÁ CHÍNH --

CREATE TABLE DEAN
(
	TENDA NVARCHAR(15),
	MADA INT NOT NULL,
	DDIEM_DA NVARCHAR(15) NOT NULL,
	PHONG INT NOT NULL,
	PRIMARY KEY (MADA)
)
GO

CREATE TABLE PHONGBAN
(
	TENPHG NVARCHAR(15),
	MAPHG INT NOT NULL,
	TRPHG NVARCHAR(9),
	NG_NHANCHUC DATE,
	PRIMARY KEY (MAPHG)
)
GO

CREATE TABLE DIADIEM_PHG
(
	MAPHG INT NOT NULL,
	DIADIEM NVARCHAR(15),
	PRIMARY KEY (MAPHG, DIADIEM)
)
GO

CREATE TABLE NHANVIEN
(
	HONV NVARCHAR(15),
	TENLOT NVARCHAR(15),
	TENNV NVARCHAR(15),
	MANV NVARCHAR(9) NOT NULL,
	NGSINH DATE,
	DCHI NVARCHAR(30),
	PHAI NVARCHAR(3),
	LUONG FLOAT,
	MA_NQL NVARCHAR(9),
	PHG INT NOT NULL,
	PRIMARY KEY (MANV)
)
GO

CREATE TABLE THANNHAN
(
	MA_NVIEN NVARCHAR(9) NOT NULL,
	TENTN NVARCHAR(15),
	PHAI NVARCHAR(3),
	NGSINH DATE,
	QUANHE NVARCHAR(15),
	PRIMARY KEY (MA_NVIEN, TENTN)
)
GO

CREATE TABLE CONGVIEC
(
	MADA INT NOT NULL,
	STT INT NOT NULL,
	TEN_CONG_VIEC NVARCHAR(50),
	PRIMARY KEY (MADA, STT)
)
GO

CREATE TABLE PHANCONG
(
	MA_NVIEN NVARCHAR(9) NOT NULL,
	MADA INT NOT NULL,
	STT INT NOT NULL,
	THOIGIAN FLOAT,
	PRIMARY KEY (MA_NVIEN, MADA, STT)
)
GO

-- TẠO KHOÁ NGOẠI --
 
ALTER TABLE DEAN
ADD CONSTRAINT FK_DEAN_PHONG
FOREIGN KEY (PHONG)
REFERENCES PHONGBAN (MAPHG)
GO

ALTER TABLE PHONGBAN
ADD CONSTRAINT FK_PHONGBAN_NHANVIEN
FOREIGN KEY (TRPHG)
REFERENCES NHANVIEN (MANV)
GO

ALTER TABLE DIADIEM_PHG
ADD CONSTRAINT FK_DIADIEM_PHG_PHONGBAN
FOREIGN KEY (MAPHG)
REFERENCES PHONGBAN (MAPHG)
GO

ALTER TABLE CONGVIEC
ADD CONSTRAINT FK_CONGVIEC_DEAN
FOREIGN KEY (MADA)
REFERENCES DEAN (MADA)
GO

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_PHONGBAN
FOREIGN KEY (PHG)
REFERENCES PHONGBAN (MAPHG)
GO

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_NHANVIEN
FOREIGN KEY (MA_NQL)
REFERENCES NHANVIEN (MANV)
GO

ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_NHANVIEN
FOREIGN KEY (MA_NVIEN)
REFERENCES NHANVIEN (MANV)
GO

ALTER TABLE THANNHAN
ADD CONSTRAINT FK_THANNHAN_NHANVIEN
FOREIGN KEY (MA_NVIEN)
REFERENCES NHANVIEN (MANV)
GO

-- THÊM DỮ LIỆU VÀO BẢNG --

BEGIN /** NHANVIEN **/
	ALTER TABLE NHANVIEN
	NOCHECK CONSTRAINT ALL
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
	VALUES (N'Đinh', N'Bá', N'Tiến', '009', '02/11/1960', N'119, Cống Quỳnh, TP.HCM', N'Nam', 30000, '005', 5)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
	VALUES (N'Nguyễn', N'Thanh', N'Tùng', '005', '08/20/1962', N'222, Nguyễn Văn Cừ, TP.HCM', N'Nam', 40000, '006', 5)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
	VALUES (N'Bùi', N'Ngọc', N'Hằng', '007', '03/11/1954', N'332, Nguyễn Thái Học, TP.HCM', N'Nam', 25000, '001', 4)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
	VALUES (N'Lê', N'Quỳnh', N'Như', '001', '02/01/1967', N'291, Hồ Văn Huê, TP.HCM', N'Nữ', 43000, '006', 4)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
	VALUES (N'Nguyễn', N'Mạnh', N'Hùng', '004', '03/04/1967', N'95, Bà Rịa - Vũng Tàu', N'Nam', 38000, '005', 5)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
	VALUES (N'Trần', N'Thanh', N'Tâm', '003', '05/04/1957', N'34, Mai Thị Lự, TP.HCM', N'Nam', 25000, '005', 5)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
	VALUES (N'Trần', N'Hồng', N'Quang', '008', '09/01/1967', N'45, Lê Hồng Phong, TP.HCM', N'Nam', 25000, '001', 4)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, PHG)
	VALUES (N'Phạm', N'Văn', N'Vinh', '006', '01/01/1965', N'45, Trưng Vương', N'Nữ', 55000, 1)
	ALTER TABLE NHANVIEN
	CHECK CONSTRAINT ALL
END
GO

BEGIN /** PHONGBAN **/
	ALTER TABLE PHONGBAN
	NOCHECK CONSTRAINT ALL
	INSERT INTO PHONGBAN (TENPHG, MAPHG, TRPHG, NG_NHANCHUC)
	VALUES (N'Nghiên cứu', 5, '005', '05/22/1978')
	INSERT INTO PHONGBAN (TENPHG, MAPHG, TRPHG, NG_NHANCHUC)
	VALUES (N'Điều hành', 4, '008', '01/01/1985')
	INSERT INTO PHONGBAN (TENPHG, MAPHG, TRPHG, NG_NHANCHUC)
	VALUES (N'Quản lý', 1, '006', '06/19/1971')
	ALTER TABLE PHONGBAN
	CHECK CONSTRAINT ALL
END
GO

BEGIN /** DEAN **/
	ALTER TABLE DEAN
	NOCHECK CONSTRAINT ALL
	INSERT INTO DEAN (TENDA, MADA, DDIEM_DA, PHONG)
	VALUES (N'Sản phẩm X', 1, N'Vũng Tàu', 5)
	INSERT INTO DEAN (TENDA, MADA, DDIEM_DA, PHONG)
	VALUES (N'Sản phẩm Y', 2, N'Nha Trang', 5)
	INSERT INTO DEAN (TENDA, MADA, DDIEM_DA, PHONG)
	VALUES (N'Sản phẩm Z', 3, N'TP.HCM', 5)
	INSERT INTO DEAN (TENDA, MADA, DDIEM_DA, PHONG)
	VALUES (N'Tin học hóa', 10, N'Hà Nội', 4)
	INSERT INTO DEAN (TENDA, MADA, DDIEM_DA, PHONG)
	VALUES (N'Cáp quang', 20, N'TP.HCM', 1)
	INSERT INTO DEAN (TENDA, MADA, DDIEM_DA, PHONG)
	VALUES (N'Đào tạo', 30, N'Hà Nội', 4)
	ALTER TABLE DEAN
	CHECK CONSTRAINT ALL
END
GO

BEGIN /** THANNHAN **/
	ALTER TABLE THANNHAN
	NOCHECK CONSTRAINT ALL
	INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
	VALUES ('005', N'Trinh', N'Nữ', '04/05/1976', N'Con gái')
	INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
	VALUES ('005', N'Khang', N'Nam', '10/25/1973', N'Con trai')
	INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
	VALUES ('005', N'Phương', N'Nữ', '05/03/1948', N'Vợ chồng')
	INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
	VALUES ('001', N'Minh', N'Nam', '02/29/1932', N'Vợ chồng')
	INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
	VALUES ('009', N'Tiến', N'Nam', '01/01/1978', N'Con trai')
	INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
	VALUES ('009', N'Châu', N'Nữ', '12/30/1978', N'Con gái')
	INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
	VALUES ('009', N'Phương', N'Nữ', '05/05/1957', N'Vợ chồng')
	ALTER TABLE THANNHAN
	CHECK CONSTRAINT ALL
END
GO

BEGIN /** DIADIEM_PHG **/
	ALTER TABLE DIADIEM_PHG
	NOCHECK CONSTRAINT ALL
	INSERT INTO DIADIEM_PHG (MAPHG, DIADIEM)
	VALUES (1, N'TP.HCM')
	INSERT INTO DIADIEM_PHG (MAPHG, DIADIEM)
	VALUES (4, N'Hà Nội')
	INSERT INTO DIADIEM_PHG (MAPHG, DIADIEM)
	VALUES (5, N'Vũng Tàu')
	INSERT INTO DIADIEM_PHG (MAPHG, DIADIEM)
	VALUES (5, N'Nha Trang')
	INSERT INTO DIADIEM_PHG (MAPHG, DIADIEM)
	VALUES (5, N'TP.HCM')
	ALTER TABLE DIADIEM_PHG
	CHECK CONSTRAINT ALL
END
GO

BEGIN /** PHANCONG **/
	ALTER TABLE PHANCONG
	NOCHECK CONSTRAINT ALL
	INSERT INTO PHANCONG (MA_NVIEN, MADA, STT, THOIGIAN)
	VALUES ('009', 1, 1, 32)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, STT, THOIGIAN)
	VALUES ('009', 2, 2, 8)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, STT, THOIGIAN)
	VALUES ('004', 3, 1, 40)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, STT, THOIGIAN)
	VALUES ('003', 1, 2, 20.0)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, STT, THOIGIAN)
	VALUES ('003', 2, 1, 20.0)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, STT, THOIGIAN)
	VALUES ('008', 10, 1, 35)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, STT, THOIGIAN)
	VALUES ('008', 30, 2, 5)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, STT, THOIGIAN)
	VALUES ('001', 30, 1, 20)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, STT, THOIGIAN)
	VALUES ('001', 20, 1, 15)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, STT, THOIGIAN)
	VALUES ('006', 20, 1, 30)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, STT, THOIGIAN)
	VALUES ('005', 3, 1, 10)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, STT, THOIGIAN)
	VALUES ('005', 10, 2, 10)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, STT, THOIGIAN)
	VALUES ('005', 20, 1, 10)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, STT, THOIGIAN)
	VALUES ('007', 30, 2, 30)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, STT, THOIGIAN)
	VALUES ('007', 10, 2, 10)
	ALTER TABLE PHANCONG
	CHECK CONSTRAINT ALL
END
GO

BEGIN /** CONGVIEC **/
	ALTER TABLE CONGVIEC
	NOCHECK CONSTRAINT ALL
	INSERT INTO CONGVIEC (MADA, STT, TEN_CONG_VIEC)
	VALUES (1, 1, N'Thiết kế sản phẩm X')
	INSERT INTO CONGVIEC (MADA, STT, TEN_CONG_VIEC)
	VALUES (1, 2, N'Thử nghiệm sản phẩm X')
	INSERT INTO CONGVIEC (MADA, STT, TEN_CONG_VIEC)
	VALUES (2, 1, N'Sản xuất sản phẩm Y')
	INSERT INTO CONGVIEC (MADA, STT, TEN_CONG_VIEC)
	VALUES (2, 2, N'Quảng cáo sản phẩm Y')
	INSERT INTO CONGVIEC (MADA, STT, TEN_CONG_VIEC)
	VALUES (3, 1, N'Khuyến mãi sản phẩm Z')
	INSERT INTO CONGVIEC (MADA, STT, TEN_CONG_VIEC)
	VALUES (10, 1, N'Tin học hóa phòng nhân sự')
	INSERT INTO CONGVIEC (MADA, STT, TEN_CONG_VIEC)
	VALUES (10, 2, N'Tin học hóa phòng kinh doanh')
	INSERT INTO CONGVIEC (MADA, STT, TEN_CONG_VIEC)
	VALUES (20, 1, N'Lắp đặt cáp quang')
	INSERT INTO CONGVIEC (MADA, STT, TEN_CONG_VIEC)
	VALUES (30, 1, N'Đào tạo nhân viên Marketing')
	INSERT INTO CONGVIEC (MADA, STT, TEN_CONG_VIEC)
	VALUES (30, 2, N'Đào tạo chuyên viên thiết kế')
	ALTER TABLE CONGVIEC
	CHECK CONSTRAINT ALL
END
GO

-- TẠO VIEW --

-- Với mỗi phòng ban, cho biết tên phòng ban, họ tên người trưởng phòng và số lượng đề án mà phòng ban đó chủ trì --
	CREATE VIEW V1
	AS
	SELECT PHONGBAN.TENPHG, (NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' ' + NHANVIEN.TENNV) AS 'Họ tên trưởng phòng', COUNT(DEAN.PHONG) AS 'Số lượng đề án'
	FROM NHANVIEN, PHONGBAN, DEAN
	WHERE NHANVIEN.MANV = PHONGBAN.TRPHG AND
		  PHONGBAN.MAPHG = DEAN.PHONG
	GROUP BY PHONGBAN.TENPHG, (NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' ' + NHANVIEN.TENNV)
	GO

-- Với mỗi phòng ban có mức lương trung bình lớn hơn 40,000, cho biết tên phòng ban và số lượng đề án mà phòng ban đó chủ trì --
	CREATE VIEW V2
	AS
	SELECT PHONGBAN.TENPHG, COUNT(DEAN.PHONG) AS 'Số lượng đề án'
	FROM NHANVIEN, PHONGBAN, DEAN
	WHERE NHANVIEN.MANV = PHONGBAN.TRPHG AND
		  PHONGBAN.MAPHG = DEAN.PHONG
	GROUP BY PHONGBAN.TENPHG
	HAVING AVG(NHANVIEN.LUONG) > 40000
	GO

-- Tên những nhân viên phòng số 5 có tham gia vào đề án "Sản phẩm X" và nhân viên này do "Nguyễn Thanh Tùng" quản lý trực tiếp.
	CREATE VIEW V3
	AS
	SELECT (NV.HONV + ' ' + NV.TENLOT + ' ' + NV.TENNV) AS 'Họ tên nhân viên phòng 5 tham gia đề án "sản phẩm X" do Nguyễn Thanh Tùng quản lý'
	FROM NHANVIEN AS NV, DEAN AS DA, PHANCONG AS PC
	WHERE NV.MANV = PC.MA_NVIEN AND DA.MADA = PC.MADA
	AND DA.TENDA = N'Sản phẩm X'AND
		  NV.MA_NQL = (SELECT NHANVIEN.MANV
							 FROM NHANVIEN
							 WHERE NHANVIEN.HONV = N'Nguyễn'AND
								   NHANVIEN.TENLOT = N'Thanh' AND
								   NHANVIEN.TENNV = N'Tùng'
							)
	GO

-- Với mỗi đề án, liệt kê tên đề án và tổng số giờ làm việc [một tuần] của tất cả các nhân viên tham dự đề án đó.
	CREATE VIEW V4
	AS
	SELECT DEAN.MADA, DEAN.TENDA, SUM(PHANCONG.THOIGIAN) as N'Tổng số giờ làm'
	FROM DEAN, PHANCONG
	WHERE DEAN.MADA = PHANCONG.MADA
	GROUP BY DEAN.MADA, DEAN.TENDA
	GO

-- ( Truy vấn lồng ) Cho biết danh sách các đề  án (MADA) có: nhân công với họ  (HONV) là 'Đinh'  hoặc  có  người  trưởng  phòng  chủ  trì  đề  án  với  họ  (HONV)  là 'Đinh'.
	CREATE VIEW V5
	AS
	SELECT PHANCONG.MADA
	FROM NHANVIEN, PHANCONG
	WHERE NHANVIEN.MANV = PHANCONG.MA_NVIEN AND
		  NHANVIEN.HONV = N'Đinh'
	UNION -- PHÉP KẾT --
	SELECT DEAN.MADA
	FROM NHANVIEN, PHONGBAN, DEAN
	WHERE NHANVIEN.MANV = PHONGBAN.TRPHG AND
		  PHONGBAN.MAPHG = DEAN.PHONG AND
		  NHANVIEN.HONV = N'Đinh'
	GO

-- Danh  sách  những  nhân  viên  (HONV,  TENLOT,  TENNV)  có  trên  2  thân nhân.
	CREATE VIEW V6
	AS
	SELECT (NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' '+ NHANVIEN.TENNV) AS 'Họ tên nhân viên có trên 2 thân nhân'
	FROM NHANVIEN, THANNHAN
	WHERE NHANVIEN.MANV= THANNHAN.MA_NVIEN
	GROUP BY (NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' '+ NHANVIEN.TENNV)
	HAVING COUNT(THANNHAN.MA_NVIEN) > 2
	GO

-- Danh sách những nhân viên (HONV, TENLOT, TENNV) không có thân nhân nào
	CREATE VIEW V7
	AS
	SELECT (NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' '+ NHANVIEN.TENNV) AS 'Danh sách những nhân viên không có thân nhân nào'
	FROM NHANVIEN
	WHERE NHANVIEN.MANV NOT IN (SELECT THANNHAN.MA_NVIEN
								FROM NHANVIEN, THANNHAN
								WHERE NHANVIEN.MANV = THANNHAN.MA_NVIEN
								)
	GO

-- Danh  sách  những  trưởng  phòng  (HONV,  TENLOT,  TENNV)  có  tối  thiểu một thân nhân.
	CREATE VIEW V8
	AS
	SELECT (NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' '+ NHANVIEN.TENNV) AS 'Họ tên trưởng phòng có ít nhất 1 thân nhân'
	FROM NHANVIEN, PHONGBAN
	WHERE NHANVIEN.MANV = PHONGBAN.TRPHG AND
		  PHONGBAN.TRPHG IN (SELECT THANNHAN.MA_NVIEN
							 FROM NHANVIEN, THANNHAN
							 WHERE NHANVIEN.MANV = THANNHAN.MA_NVIEN
							 )
	GO

-- Tìm họ (HONV) của những trưởng phòng chưa có gia đình.
	CREATE VIEW V9
	AS
	SELECT NHANVIEN.HONV
	FROM NHANVIEN, PHONGBAN
	WHERE NHANVIEN.MANV = PHONGBAN.TRPHG AND
		  PHONGBAN.TRPHG NOT IN (SELECT PHONGBAN.TRPHG
								 FROM PHONGBAN, THANNHAN
								 WHERE PHONGBAN.TRPHG = THANNHAN.MA_NVIEN AND
									  THANNHAN.QUANHE = N'Vợ chồng'
								 )
	GO

-- Cho biết họ tên nhân viên (HONV, TENLOT, TENNV) có mức lương trên mức lương trung bình của phòng "Nghiên cứu"
	CREATE VIEW V10
	AS
	SELECT (NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' ' + NHANVIEN.TENNV) AS 'Họ tên nhân viên có lương trung bình trên mức lương trung bình của phòng "Nghiên cứu"'
	FROM NHANVIEN
	WHERE NHANVIEN.LUONG > (SELECT AVG(NHANVIEN.LUONG)
							FROM NHANVIEN, PHONGBAN
							WHERE NHANVIEN.PHG = PHONGBAN.MAPHG AND
								  PHONGBAN.TENPHG = N'Nghiên cứu')
	GO

-- Cho biết tên phòng ban và họ tên trưởng phòng của phòng ban có đông nhân viên nhất
	CREATE VIEW V11 AS
	WITH DepartmentCount AS (
	SELECT PHG, COUNT(*) as EmployeeCount
	FROM NHANVIEN
	GROUP BY PHG
	)
	SELECT PHONGBAN.TENPHG AS "Tên Phòng Ban", NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' ' + NHANVIEN.TENNV AS " Tên Trưởng Phòng"
	FROM DepartmentCount
	JOIN PHONGBAN ON DepartmentCount.PHG = PHONGBAN.MAPHG
	JOIN NHANVIEN ON PHONGBAN.TRPHG = NHANVIEN.MANV
	WHERE EmployeeCount = (SELECT MAX(EmployeeCount) FROM DepartmentCount);
	GO

-- Cho biết danh sách các mã đề án mà nhân viên có mã là 009 chưa làm.
	CREATE VIEW V12
	AS
	SELECT DEAN.MADA as N'Danh sách các mã đề án mà nhân viên có mã là 009 chưa làm'
	FROM DEAN
	WHERE DEAN.MADA NOT IN (SELECT PHANCONG.MADA
							FROM PHANCONG
							WHERE PHANCONG.MA_NVIEN = '009'
							)
	GO

-- Cho biết danh sách các công việc (tên công việc) trong đề án "Sản phẩm X" mà nhân viên có mã là 009 chưa làm.
	CREATE VIEW V13
	AS
	SELECT CONGVIEC.TEN_CONG_VIEC as N'Danh sách các công việc (tên công việc) trong đề án "Sản phẩm X" mà nhân viên có mã là 009 chưa làm '
	FROM CONGVIEC, DEAN
	WHERE CONGVIEC.MADA = DEAN.MADA AND
		  DEAN.TENDA = N'Sản phẩm X' AND
		  CONGVIEC.TEN_CONG_VIEC NOT IN (SELECT CONGVIEC.TEN_CONG_VIEC
										 FROM CONGVIEC, PHANCONG
										 WHERE CONGVIEC.MADA = PHANCONG.MADA AND
										 PHANCONG.MA_NVIEN = '009')
	GO

-- Tạo Thủ Tục (STORE PROCEDURE) --

-- Thủ tục cập nhật phòng ban với tham số đầu vào là maphg --
CREATE PROCEDURE Update_Name_PhongBan_With_MAPHG (@maphg INT)
AS
BEGIN
    DECLARE @newname NVARCHAR(15)
    SET @newname = N'Quản Lý' -- Hãy thay đổi tên phòng ban cần cập nhật ở đây --

    UPDATE PHONGBAN
    SET TENPHG = @newname
    WHERE MAPHG = @maphg
END
GO

-- Thủ tục thêm vào thân nhân của nhân viên với những nhân viên là trưởng phòng --
CREATE PROC ADD_THANNHAN_IS__TRPHG
	(	@MA_NVIEN NVARCHAR (15),
		@TENTN NVARCHAR (15),
		@PHAI NVARCHAR (3),
		@NGSINH DATE,
		@QUANHE NVARCHAR (15)
	)

	AS
	BEGIN
	IF ( @MA_NVIEN IN (SELECT PHONGBAN.TRPHG FROM PHONGBAN, NHANVIEN WHERE NHANVIEN.MANV = PHONGBAN.TRPHG))
		BEGIN
		INSERT INTO THANNHAN
	     VALUES (@MA_NVIEN,
			     @TENTN,
			     @PHAI,
			     @NGSINH,
			     @QUANHE)
		PRINT N'Thêm Thân Nhân Thành Công'
		END
	ELSE
		BEGIN 
			PRINT N'Thêm thân nhân thất bại, người này không phải là thân nhân của trưởng phòng'
		END
	END
GO

/*

EXEC ADD_THANNHAN_IS__TRPHG '005', 'Thân nhân 1', 'Nam', '1990-01-01', 'Anh em' -- ĐÂY LÀ CÂU LỆNH TEST, NẾU THÊM THÀNH CÔNG THÌ LÀ ĐÚNG --
GO

EXEC ADD_THANNHAN_IS__TRPHG '001', 'Thân nhân 1', 'Nam', '1990-01-01', 'Anh em' -- ĐÂY LÀ CÂU LỆNH TEST, NẾU THÊM KHÔNG THÀNH CÔNG THÌ LÀ ĐÚNG --
GO

*/

-- Thủ tục thêm vào một phòng ban trong bảng phongban với các tham số đầu vào tenphg, maphg, trphg, ng_nhanchuc --
CREATE PROCEDURE ADD_PHONG_BAN (@tenphg NVARCHAR(50), @maphg INT, @trphg INT, @ng_nhanchuc DATE)
AS
BEGIN
	INSERT INTO PHONGBAN (TENPHG, MAPHG, TRPHG, NG_NHANCHUC)
	VALUES (@tenphg, @maphg, @trphg, @ng_nhanchuc)
END
GO

-- Tạo thủ tục cập nhật thân nhân của nhân viên với những nhân viên là trưởng phòng --
	CREATE PROCEDURE UPDATE_THANNHAN_IS_TRUONGPHG
	(
	@MANV NVARCHAR(9),
	@TENTN NVARCHAR(15),
	@PHAI NVARCHAR(3),
	@NGSINH DATE,
	@QUANHE NVARCHAR(15)
	)
	AS
	BEGIN
	DECLARE @rowcount INT
	DECLARE @MADA INT
	DECLARE @TRPHG NVARCHAR(9)
	SELECT @MADA = MADA FROM DEAN WHERE DDIEM_DA = (SELECT DCHI FROM NHANVIEN WHERE MANV = @MANV)
	SELECT @TRPHG = TRPHG FROM PHONGBAN WHERE MAPHG = (SELECT PHG FROM NHANVIEN WHERE MANV = @MANV)
	IF @MANV = @TRPHG
		BEGIN
			UPDATE THANNHAN
			SET PHAI = @PHAI, NGSINH = @NGSINH, QUANHE = @QUANHE
			WHERE MA_NVIEN = @MANV AND TENTN = @TENTN
			SET @rowcount = @@ROWCOUNT

			IF @rowcount = 1
				 BEGIN
				PRINT N'Cập nhật thân nhân thành công'
				 END
			ELSE
				BEGIN
				PRINT N'Cập nhật thân nhân thất bại, có vẻ như thân nhân này không phải là thân nhân của trưởng phòng có mã nhân viên là: ' +@MANV
					END
		END
	ELSE
				BEGIN
				PRINT N'Cập nhật thân nhân thất bại, vì thân nhân này không phải là thân nhân của trưởng phòng'
					END
	END
	GO

/*

Câu lệnh TEST

EXEC Update_ThanNhan_IS_TruongPHG 
@MANV = '005', @TENTN = 'Khang', @PHAI = 'Nam', @NGSINH = '1973-10-25', @QUANHE = N'Con trai'

*/